### ISSUE TITLE
Noob Question Please help.

### ISSUE THREAD

**Issue by Daxcor69** [hanford/await-exec#2]
This is not an issue of an error with your code, this is me just not getting how to use your wrapper.  To  be honest I am struggling with async/await and promise and call back. I am old school and async coding has been really hard to learn. This issue is fundamental to how I understand how to use async await.  Any help would be greatly appreciated.

```
const dirArray = [
  '/home/brad/Data/modules',
  '/home/brad/Data/systems',
  '/home/brad/Data/worlds',
  '/home/brad/Data/worlds/world_1',
  '/home/brad/Data/worlds/world_2',
];
const myexec = require('await-exec');

const myob = get(dirArray);
console.log(myob);

async function get(dirArray) {
    let myarrobj = [];
    let myobj = {};
    let myparams = {};
    dirArray.forEach((dirArray) => {
        await myexec(`du -sh ${dirArray}`); 
        console.log(size);
        mysize = size.stdout.split('\t');
        myobj['size'] = mysize[0];
        myobj['name'] = dirArray;
        myarrobj.push(myobj);
        myobj = {};
        console.log(myarrobj);
    });
    return myarrobj;
}
```
The error I get when I run this is 
```
await myexec(`du -sh ${dirArray}`); 
        ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by hanford** [comment]
@Daxcor69 I don't think you can use async/await in `.forEach`

https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop
